### ISSUE TITLE
VOI_normalized crashes when arguments incorrect

### ISSUE THREAD

**Issue by jura-gresko** [panda-official/metric#153]
```
std::vector<std::vector<double>> v21 = { { 5, 5 }, { 2, 2 }, { 3, 3 }, { 5, 5 } };
std::vector<std::vector<double>> v22 = { { 5, 5 }, { 2, 2 }, { 3, 3 }, { 1, 1 } };
auto voi = metric::VOI_normalized<double>();
std::cout << voi(v21, v22) << std::endl;       // <-- crash here
```
I took this code snippet from
https://github.com/panda-official/metric/blob/dea1a9209f73c9df80b6594eae49fdb108dde150/tests/distance_tests/voi_tests.cpp#L138

According to @mkh-welsch 
> VOI_normalized is outdated since the last entropy update and tries to use old code

**Comment by mkh-welsch** [comment]
we have a problem with the asserts p<k<n. 

how do we proceed. check and override the values?

also, I'm not sure, if the algorithm delivers meaningful results for small data sets.

**Comment by mkh-welsch** [comment]
@maxfilippov : can you please think about and update, when you finish and clean up the code.

**Comment by maxfilippov** [comment]
Failure on p, k greater than dataset fixed by changing params internally to nearest feasable values. I think we should somehow inform user when the  value is returned but parameters he provided are wrong and replaced. I think we need some general policy for this.

Also added nan return on dataset smaller than 4 (it'd be better to make the cutoff greater, but this way we can not provide small examples).

commit
https://github.com/panda-official/metric/commit/cd299725afb9928a22e3c1e3880ed2e1ef94283d
